import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: .workspaceName,
  projects: [
    "Projects/App",
    "Projects/Domain",
    "Projects/DesignSystem",
    "Projects/Shared"
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: "26.1"
  )
)
